context:
  version: "12.0.0"

package:
  name: nestjs-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@nestjs/cli/-/cli-${{ version }}.tgz
  sha256: ec1b0c17b7db7396c31efd815a5f2c0a14a07ffa53ddd2a451b7d9d4512a00d9

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - nest --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Nest - modern, fast, powerful node.js web framework (@cli)
  homepage: https://github.com/nestjs/nest-cli
  repository: https://github.com/nestjs/nest-cli

extra:
  recipe-maintainers:
    - danielnachun
